setup-environment-internal: fix several issues
This patch contains the following fixes:
- Change 'LMP' to 'Torizoncore'.
- Return '1' instead of empty when there is a error arised.
- Redirect error messgage to stderr rather than stdout.
- Check cmdline parameters earlier before any variable assignments.

Related-to: TOR-950
Signed-off-by: Ming Liu <ming.liu@toradex.com>

diff --git a/scripts/setup-environment-internal b/scripts/setup-environment-internal
--- a/scripts/setup-environment-internal
+++ b/scripts/setup-environment-internal
@@ -28,11 +28,28 @@ env_cleanup() {
         export BUILDDIR
     fi
 }
+
+usage () {
+    cat >&2 <<EOF
+
+Usage: [MACHINE=<MACHINE>] source ${BASH_SOURCE[0]} [BUILDDIR]
+
+If no MACHINE is set, list all possible machines, and ask user to choose.
+If no BUILDIR is set, it will be set to build-$DISTRO.
+
+EOF
+}
+
 trap env_cleanup RETURN
 
 if [ "$(whoami)" = "root" ]; then
-    echo "ERROR: do not build LMP as root. Exiting..."
-    return
+    echo "ERROR: do not build Torizoncore as root. Exiting..." >&2
+    return 1
+fi
+
+if [ $# -gt 1 ]; then
+    usage
+    return 1
 fi
 
 OEROOT=$(pwd)
@@ -46,22 +63,6 @@ fi
 
 # Set default distro to Linux microPlatform
 DISTRO=torizon
-
-usage () {
-    cat <<EOF
-
-Usage: [MACHINE=<MACHINE>] source ${BASH_SOURCE[0]} [BUILDDIR]
-
-If no MACHINE is set, list all possible machines, and ask user to choose.
-If no BUILDIR is set, it will be set to build-$DISTRO.
-
-EOF
-}
-
-if [ $# -gt 1 ]; then
-    usage
-    return 1
-fi
 
 # Create a common list of "<machine>(<layer>)", sorted by <machine>
 # Blacklist OE-core, we only want BSP layers
@@ -110,7 +111,7 @@ if [ -z "$MACHINE" ]; then
     read -r
     echo "$MACHLAYERS" | sed -e 's/(/ (/g' | sed -e 's/)/)\n/g' |
             sed -e 's/^ */\t/g'
-    return
+    return 1
 fi
 
 if [ -z "${SDKMACHINE}" ]; then
